platform :ios, '16.0'          # puedes bajar a 13/12 si necesitas soportar más

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Asegura que se carguen categorías ObjC (evita undefined symbols tipo GTMLogger)
      config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -ObjC'
      # Asegura versión Swift si falta (Xcode 15)
      config.build_settings['SWIFT_VERSION'] ||= '5.0'
      # Permitir arm64 en simulador (mobile_scanner y MLKit lo excluyen en su podspec,
      # rompiendo simuladores Apple Silicon como iPhone 15)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end

  # Algunos pods (mobile_scanner, MLKit*) escriben EXCLUDED_ARCHS=arm64 directamente
  # en su .xcconfig, lo cual sobreescribe los build_settings de arriba. Hay que
  # parchear esos archivos para que el simulador en Apple Silicon pueda compilar.
  Dir.glob(File.join(installer.sandbox.target_support_files_root, '**', '*.xcconfig')).each do |xcconfig|
    contents = File.read(xcconfig)
    new_contents = contents.gsub(/^EXCLUDED_ARCHS\[sdk=iphonesimulator\*\].*$/, 'EXCLUDED_ARCHS[sdk=iphonesimulator*] = ')
    File.write(xcconfig, new_contents) if new_contents != contents
  end
end

